apiVersion: v1
kind: Service
metadata:
  name: student-management-service
spec:
  selector:
    app: student-management
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
